name: Publish NuGet

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Publish NuGet
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        PROJECT_FILE_PATH: NetProjTest/NetProjTest.csproj
        VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
